export const ADD_CURRENT_INGREDIENTS = "ADD_CURRENT_INGREDIENTS";
export const ADD_CURRENT_BUN = "ADD_CURRENT_BUN";
export const BURGER = "BURGER";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const CHANGE_BUN = "CHANGE_BUN";
