export const CURRENT_ORDER_REQUEST: "CURRENT_ORDER_REQUEST" =
  "CURRENT_ORDER_REQUEST";
export const CURRENT_ORDER_SUCCESS: "CURRENT_ORDER_SUCCESS" =
  "CURRENT_ORDER_SUCCESS";
export const CURRENT_ORDER_FAILURE: "CURRENT_ORDER_FAILURE" =
  "CURRENT_ORDER_FAILURE";
export const CURRENT_ORDER_RESET: "CURRENT_ORDER_RESET" = "CURRENT_ORDER_RESET";
