export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_RESET: "REGISTER_RESET" = "REGISTER_RESET";
export const REGISTER_FAILURE: "REGISTER_FAILURE" = "REGISTER_FAILURE";
